# -*- coding: utf-8 -*-
"""Content of the role cards (French, taken from the design document).

Each role: key (RoleType name), name, faction, objective, mining (list of bullets, phase de
minage) and finale (list of bullets, phase finale / arène).  Keep every bullet short: the
generator wraps the text and shrinks the font if a card overflows.
"""

FACTIONS = {
    "Imanity": "#d9534f",
    "Flügel": "#c77dff",
    "Werebeasts": "#f0a030",
    "Ex-Machina": "#38c6d9",
    "Elves": "#4cc36a",
    "Old Deus": "#8a4fd6",
    "Autres": "#9a9a9a",
}

ROLES = [
    # ------------------------------------------------------------------ Imanity
    dict(key="SORA", name="Sora", faction="Imanity", duo="Shiro",
         objective="Gagner avec Shiro.",
         mining=["Au lancement d'un mini-jeu, 30 s pour demander à Shiro d'y aller à ta place (/substitute).",
                 "Tu connais l'identité et la position de Shiro dès le début."],
         finale=["Couronne : 5 clones autour de toi pendant 10 s (toutes les 20 min).",
                 "Proche de Shiro (30 blocs) : Résistance + Vitesse. Plus loin : Faiblesse."]),
    dict(key="SHIRO", name="Shiro", faction="Imanity", duo="Sora",
         objective="Gagner avec Sora.",
         mining=["Au lancement d'un mini-jeu, tu peux donner un bonus à Sora (2 fois par partie, /bonus).",
                 "Tu connais l'identité et la position de Sora dès le début."],
         finale=["Couronne : 5 clones autour de toi pendant 10 s (toutes les 20 min).",
                 "Proche de Sora (30 blocs) : Résistance + Vitesse. Plus loin : Faiblesse."]),
    dict(key="STEPHANIE", name="Stéphanie Dola", faction="Imanity", duo="Makoto",
         objective="Gagner avec Makoto.",
         mining=["Une fois par partie, tu choisis le mini-jeu (si tu as gagné le PvP).",
                 "Vitesse I pendant Parkour et The Floor Is Lava."],
         finale=["Love Gun : touche un joueur pour le mettre à 6 cœurs pendant 30 s (toutes les 10 min)."]),
    dict(key="MAKOTO", name="Makoto Dola", faction="Imanity", duo="Stéphanie",
         objective="Gagner avec Stéphanie.",
         mining=["Une fois par partie, tu peux annuler une défaite de mini-jeu (/duo cancel).",
                 "Aucun effet pendant les mini-jeux."],
         finale=["Si Stéphanie meurt, tu t'allies automatiquement avec le joueur qui a gagné le plus de mini-jeux."]),
    dict(key="RIKU", name="Riku Dola", faction="Imanity", duo="Schwi",
         objective="Gagner avec Schwi.",
         mining=["Chaque mini-jeu gagné te donne 1 cœur en plus.",
                 "Si tu survis 5 min après la mort de Schwi, elle revient à tes côtés (vous perdez 3 cœurs chacun)."],
         finale=["Si Schwi est sous 3 cœurs : Force II pendant 30 s.",
                 "/heal : donne 2 PV à Schwi (illimité)."]),
    dict(key="CORONE", name="Corone Dola", faction="Imanity", duo=None,
         objective="Gagner seule ou en alliance (/alliance).",
         mining=["Tu connais l'identité de Riku.",
                 "Régénération automatique."],
         finale=["Tu vois 179 Ghost même invisible.",
                 "Si Ivan meurt, Nonna peut te rejoindre : Vitesse I pour vous deux."]),
    dict(key="EINZIG", name="Einzig", faction="Imanity", duo=None,
         objective="Gagner seul ou en alliance (/alliance).",
         mining=["Tu connais l'identité de Sora."],
         finale=["Deux vies : d'abord un homme faible (Faiblesse II, 10 cœurs),",
                 "puis Force et 8 cœurs après ta première mort.",
                 "Si tu tues Riku, tu rejoins le camp de Sora."]),
    # ------------------------------------------------------------------ Flügel
    dict(key="JIBRIL", name="Jibril", faction="Flügel", duo=None,
         objective="Gagner seule ou en alliance (/alliance).",
         mining=["Aucun avantage en mini-jeu.",
                 "Régénération automatique."],
         finale=["Livre des 18 ailes : une catastrophe aléatoire (nucléaire, lave, cratère, zone radioactive).",
                 "Tu ne subis aucun dégât de tes catastrophes (toutes les 20 min)."]),
    dict(key="AZRIEL", name="Azriel", faction="Flügel", duo=None,
         objective="Gagner seule ou en alliance (/alliance).",
         mining=["Tu détectes les mouvements des Flügel dans un rayon de 50 blocs.",
                 "Une fois par épisode, tu copies temporairement le pouvoir d'un Flügel proche."],
         finale=["Zone anti-vol : le vol est désactivé 30 s autour de toi (toutes les 20 min)."]),
    # ------------------------------------------------------------------ Werebeasts
    dict(key="IZUNA", name="Izuna Hatsuse", faction="Werebeasts", duo="Ino",
         objective="Gagner avec Ino.",
         mining=["Tu aveugles ton adversaire pendant le Bloc Party."],
         finale=["Vitesse II et une flèche qui te guide vers Ino.",
                 "Si Ino meurt : couronne de 5 clones (10 s, toutes les 20 min)",
                 "et tu peux rejoindre Miko (Faiblesse II pendant 5 min)."]),
    dict(key="INO", name="Ino Hatsuse", faction="Werebeasts", duo="Izuna",
         objective="Gagner avec Izuna.",
         mining=["Tu ralentis ton adversaire pendant TNT Run et Splegg."],
         finale=["Bouclier Hatsuse : Izuna est invincible, invisible et ne peut pas frapper pendant 30 s (toutes les 20 min).",
                 "Si Izuna meurt : Force II 10 s pour tuer son meurtrier, sinon tu meurs avec elle."]),
    dict(key="PLUM", name="Plum", faction="Werebeasts", duo=None,
         objective="Gagner seule ou en alliance (/alliance).",
         mining=["Tu vois les contours des joueurs dans le noir.",
                 "3 dispositifs d'écoute qui enregistrent les conversations (20 % de risque d'être repérés à 5 blocs)."],
         finale=["Sort de cécité : aveugle les ennemis proches (toutes les 15 min)."]),
    # ------------------------------------------------------------------ Ex-Machina
    dict(key="SCHWI", name="Schwi Dola", faction="Ex-Machina", duo="Riku",
         objective="Gagner avec Riku.",
         mining=["Vitesse et Saut amélioré dans TOUS les mini-jeux.",
                 "Si Riku meurt, tu meurs de tristesse."],
         finale=["Force (réduite) et une Alliance : les ennemis à moins de 30 blocs brillent (toutes les 10 min)."]),
    dict(key="SHI", name="Shi", faction="Ex-Machina", duo="Kū",
         objective="Gagner avec Kū.",
         mining=["Ta santé est partagée avec Kū : il faut vous éliminer tous les deux.",
                 "Tu analyses les mini-jeux passés de ton adversaire."],
         finale=["Noyau de sécurité : zone où aucun dégât ne peut être infligé (toutes les 20 min)."]),
    dict(key="KU", name="Kū", faction="Ex-Machina", duo="Shi",
         objective="Gagner avec Shi.",
         mining=["Ta santé est partagée avec Shi.",
                 "Ton scanner détecte les porteurs d'objets spéciaux à 30 blocs."],
         finale=["Impulsion de réparation : répare tout l'équipement de Shi (toutes les 20 min)."]),
    # ------------------------------------------------------------------ Elves
    dict(key="KURAMI", name="Kurami Zell", faction="Elves", duo="Feel",
         objective="Gagner avec Feel.",
         mining=["Une fois par partie, lie un mini-jeu à Feel : en cas de défaite, vous tombez tous deux à 5 cœurs.",
                 "Deux vies au Dés à coudre et au Bloc Party."],
         finale=["Oracle Card : échange la place de 2 joueurs hors combat (toutes les 20 min).",
                 "20 % de risque d'être téléportée à la place de l'un d'eux."]),
    dict(key="FEEL", name="Feel Nilvalen", faction="Elves", duo="Kurami",
         objective="Gagner avec Kurami.",
         mining=["Une fois par partie, lie un mini-jeu à Kurami : en cas de défaite, vous tombez tous deux à 5 cœurs.",
                 "Deux vies à Anvil Rain et The Floor Is Lava."],
         finale=["Oracle Card : téléporte-toi auprès de Kurami, invisible 30 s (toutes les 20 min)."]),
    dict(key="FIEL", name="Fiel", faction="Elves", duo="Chlammy",
         objective="Gagner avec Chlammy.",
         mining=["Une fois par épisode, crée une illusion de toi et échange ta place avec elle (1 fois par partie).",
                 "Tu connais l'identité et la position de Chlammy."],
         finale=["Masque d'illusion : prends l'apparence d'un autre joueur pendant 30 s (toutes les 15 min)."]),
    dict(key="CHLAMMY", name="Chlammy", faction="Elves", duo="Fiel",
         objective="Gagner avec Fiel.",
         mining=["Une fois par épisode, lis l'esprit d'un joueur pour connaître son inventaire.",
                 "Tu connais l'identité et la position de Fiel."],
         finale=["Orbe de prédiction : ralentit un adversaire proche pendant 20 s (toutes les 15 min)."]),
    dict(key="THINK", name="Think Nirvalen", faction="Elves", duo=None,
         objective="Gagner seul (aucune alliance).",
         mining=["Tu connais la position de l'Aka Si Anse.",
                 "Chaque kill te rapporte 1 cœur supplémentaire."],
         finale=["/rite 1 : invisible et vol pendant 2 min (prend fin au premier dégât).",
                 "/rite 2 : Lévitation sur un joueur pendant 5 s.",
                 "Une seule utilisation par rite."]),
    # ------------------------------------------------------------------ Old Deus
    dict(key="ARTOSH", name="Artosh", faction="Old Deus", duo=None,
         objective="Gagner seul ou en alliance (/alliance).",
         mining=["Tu apprends qui est Schwi (40 % de chance d'info fausse).",
                 "Force pendant 5 min après chaque kill."],
         finale=["18 Ailes (élytres) pour planer entre les bâtiments.",
                 "Lame de l'Infini : tue les ennemis à moins de 2 cœurs dans 5 blocs (+1 cœur par kill).",
                 "Les dégâts de Jibril sur toi sont doublés."]),
    dict(key="OKEIN", name="Ōkein", faction="Old Deus", duo=None,
         objective="Gagner seul ou en alliance (/alliance).",
         mining=["Tu connais le rôle du premier joueur blessé.",
                 "Enclume, 200 niveaux, Résistance au feu, livre Flame : seul à pouvoir utiliser le feu.",
                 "L'eau te brûle (1 cœur/s)."],
         finale=["Marteau de destruction : pluie d'enclumes 5x5, 4 cœurs chacune (toutes les 15 min, 5 si kill)."]),
    dict(key="KAINAS", name="Kainas", faction="Old Deus", duo=None,
         objective="Gagner seul ou en alliance (/alliance).",
         mining=["Tu connais le rôle du premier joueur à obtenir la régénération.",
                 "/forest : tout le végétal à l'infini.",
                 "Le feu te fait des dégâts doublés."],
         finale=["Cage végétale 5x5 pendant 1 min : régénération + vitesse pour toi, Lenteur II pour les autres (15 min, 10 si kill)."]),
    dict(key="TETO", name="Teto", faction="Old Deus", duo=None,
         objective="Gagner seul ou en alliance (/alliance).",
         mining=["Tu connais le rôle d'un joueur de ton choix.",
                 "Tu choisis toujours le mini-jeu, même sans gagner le PvP."],
         finale=["Roi d'échec : invincible 10 s, ta position est révélée, −2 cœurs (toutes les 10 min).",
                 "Rappel royal : ressuscite le joueur de ton choix, il devient ton allié."]),
    dict(key="HOLOU", name="Holou", faction="Old Deus", duo=None,
         objective="Gagner seul ou en alliance (/alliance).",
         mining=["Au début, cache les pseudos et rôles des morts contre 2 cœurs (toi seul les vois).",
                 "/teleport <joueur> <joueur> : échange la place de 2 joueurs (1 fois), ils reçoivent un livre aléatoire."],
         finale=["Bâton de téléportation : à 30 blocs du joueur de ton choix, aveugle 5 s (toutes les 10 min).",
                 "Aucun dégât des catastrophes de Jibril."]),
    # ------------------------------------------------------------------ Autres
    dict(key="IVAN", name="Ivan Zell", faction="Autres", duo="Nonna",
         objective="Gagner avec Nonna.",
         mining=["Bâton de recul au Sumo (1 utilisation par manche).",
                 "Tu connais Riku et Nonna sans savoir qui est qui (10 % d'info fausse)."],
         finale=["ID Helmet (fer, Protection I) : révèle les traces de pas des joueurs pendant 10 s."]),
    dict(key="NONNA", name="Nonna Zell", faction="Autres", duo="Ivan",
         objective="Gagner avec Ivan.",
         mining=["Bâton de recul au Sumo (1 utilisation par manche)."],
         finale=["Oracle Card : téléporte un joueur au hasard sur la carte (20 % de risque que ce soit toi).",
                 "Si Ivan meurt : rejoins Corone (Vitesse I) ou Riku et Schwi (Faiblesse à moins de 10 blocs de Riku)."]),
    dict(key="MIKO", name="Miko", faction="Autres", duo=None,
         objective="Gagner seule ou en alliance (/alliance).",
         mining=["Tu connais l'identité de Riku.",
                 "12 cœurs pendant toute la partie."],
         finale=["Œil mécanique : fait revenir les joueurs proches 10 s en arrière (toutes les 20 min).",
                 "Si Ino meurt, Izuna peut te rejoindre : Hâte II pour vous deux."]),
    dict(key="GHOST", name="179 Ghost", faction="Autres", duo=None,
         objective="Gagner seul ou en alliance (/alliance).",
         mining=["Tu reçois les identités de Riku, Corone, Lily et Schwi (sans savoir qui est qui)."],
         finale=["Invisible, Vitesse II, pas de dégâts de chute, mais tu ne peux pas attaquer.",
                 "Objet Fantôme : redeviens visible (5 min avant de pouvoir disparaître).",
                 "Si tu tues Corone, elle rejoint ton équipe."]),
]
